export const ROUTES = {
    LOGIN: '/login',
    RECUPERAR_SENHA: '/recuperar-senha',
    DASHBOARD: '/dashboard',
    ALUNOS: '/alunos',
    ALUNO_NOVO: '/alunos/novo',
    ALUNO_DETALHE: (id: string) => `/alunos/${id}`,
    CANDIDATOS: '/candidatos',
    CANDIDATO_DETALHE: (id: string) => `/candidatos/${id}`,
    CONTRATOS: '/contratos',
    CONTRATO_NOVO: '/contratos/novo',
    CONTRATO_DETALHE: (id: string) => `/contratos/${id}`,
    FINANCEIRO: '/financeiro',
    FINANCEIRO_FLUXO: '/financeiro/fluxo-de-caixa',
    FINANCEIRO_INADIMPLENCIA: '/financeiro/inadimplencia',
    FINANCEIRO_RELATORIOS: '/financeiro/relatorios',
    AULAS: '/aulas',
    AULA_NOVA: '/aulas/nova',
    AULAS_SERIES: '/aulas/series',
    AULA_DETALHE: (id: string) => `/aulas/${id}`,
    PRESENCA: '/presenca',
    PRESENCA_AULA: (aulaId: string) => `/presenca/${aulaId}`,
    FEED: '/feed',
    FEED_NOVO_POST: '/feed/novo-post',
    STORIES: '/stories',
    STORY_NOVO: '/stories/novo',
    EVENTOS: '/eventos',
    EVENTO_NOVO: '/eventos/novo',
    NOTIFICACOES: '/notificacoes',
    CONFIGURACOES: '/configuracoes',
    CONFIG_PLANOS: '/configuracoes/planos',
    CONFIG_PERFIL: '/configuracoes/perfil',
} as const
